//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_iFINANCEAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group3_iFINANCEDBEntities : DbContext
    {
        public Group3_iFINANCEDBEntities()
            : base("name=Group3_iFINANCEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCategory> AccountCategory { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<NonAdminUser> NonAdminUser { get; set; }
        public virtual DbSet<UserPassword> UserPassword { get; set; }
    }
}
